CREATE TABLE IF NOT EXISTS identity (id INTEGER PRIMARY KEY CHECK(id=1), scope TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS blobs (hash TEXT PRIMARY KEY, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS captures (id TEXT PRIMARY KEY, source TEXT NOT NULL, session TEXT NOT NULL,
    repo TEXT NOT NULL, body TEXT NOT NULL, status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS plans (id TEXT PRIMARY KEY, capture TEXT NOT NULL REFERENCES captures(id), body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS attempts (key TEXT NOT NULL, attempt INTEGER NOT NULL, reserved INTEGER NOT NULL,
    status TEXT NOT NULL, response TEXT, PRIMARY KEY(key,attempt));
CREATE TABLE IF NOT EXISTS selections (hash TEXT NOT NULL, anchor TEXT NOT NULL, irrelevant INTEGER NOT NULL,
    receipt TEXT NOT NULL, PRIMARY KEY(hash,anchor));
CREATE TABLE IF NOT EXISTS knowledge (id INTEGER PRIMARY KEY CHECK(id=1), body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS publication (id INTEGER PRIMARY KEY CHECK(id=1), predecessor TEXT);
CREATE TABLE IF NOT EXISTS processed (key TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS normalized_sources (hash TEXT PRIMARY KEY, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS tool_sources (source TEXT NOT NULL, session TEXT NOT NULL, repo TEXT NOT NULL,
    message TEXT NOT NULL, call_id TEXT NOT NULL, hash TEXT NOT NULL REFERENCES blobs(hash),
    PRIMARY KEY(source,session,repo,message,call_id));
